### ISSUE TITLE
About the cal_metrics.py file

### ISSUE THREAD

**Issue by gwakjaeha** [LeaveYeah/BioNumQA-BERT#2]
Thanks for sharing the source.

There is a file cal_metrics.py inside the test.sh file, but it is not uploaded.
Could you please share the cal_metrics.py file?'

Thank you

**Comment by LeaveYeah** [comment]
Sorry for the late replay. The file has been uploaded. 

Wish you a happy lunar new year.

Best,
Alex

**Comment by gwakjaeha** [comment]
I checked the uploaded file.
Thank you for your kindness. Happy New Year to you too.

-Jaeha



2022년 2월 4일 (금) 오후 12:41, LeaveYeah ***@***.***>님이 작성:
